#ifndef DEXPROS_DRIVERS_KEYBOARD_PS2KEYBOARDSCANCODES_H_INCLUDED
#define DEXPROS_DRIVERS_KEYBOARD_PS2KEYBOARDSCANCODES_H_INCLUDED

#include "DexprOS/Kernel/KeyboardInput.h"
#include "DexprOS/Kernel/Memory/MemoryDef.h"

#include <stdint.h>
#include <stddef.h>


typedef enum DexprOS_PS2KeyboardKeyAction
{
    DEXPROS_PS2K_NONE = 0,
    DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED,
    DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED,
    DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED_RELEASED
} PS2KeyboardKeyAction;

typedef struct DexprOS_PS2KeyboardMapKey
{
    DexprOS_KeyID keyID;
    PS2KeyboardKeyAction keyAction;
} PS2KeyboardMapKey;

typedef struct DexprOS_PS2KeyboardSpecialSequence
{
    PS2KeyboardMapKey key;

    const uint8_t* pSequence;
    uint8_t sequenceLength;
} PS2KeyboardSpecialSequence;

typedef struct DexprOS_PS2KeyboardScanCodes PS2KeyboardScanCodes;
struct DexprOS_PS2KeyboardScanCodes
{
    const PS2KeyboardMapKey* pKeysPerByte;
    uint8_t numKeysPerByte;

    const PS2KeyboardScanCodes* pByteExtendedScanCodes;
    const uint8_t* pByteExtendCodes;
    uint8_t numByteExtendCodes;

    const PS2KeyboardSpecialSequence* pSpecialSequences;
    uint8_t numSpecialSequences;
};


static PS2KeyboardMapKey g_scanCode2SingleByteSet[133] = {
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_F9, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F7, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED}, // F7 is 0x02 on some laptop keyboards
    {DEXPROS_KEY_F5, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F3, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F1, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F2, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F12, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_F10, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F8, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F6, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F4, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_TAB, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_GRAVE_ACCENT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT_ALT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_LEFT_SHIFT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT_CONTROL, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_Q, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_1, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_Z, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_S, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_A, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_W, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_2, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_C, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_X, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_D, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_E, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_4, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_3, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_SPACE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_V, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_T, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_R, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_5, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_N, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_B, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_H, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_G, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_Y, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_6, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_M, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_J, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_U, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_7, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_8, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_COMMA, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_K, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_I, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_O, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_0, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_9, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_PERIOD, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_SLASH, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_L, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_SEMICOLON, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_P, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MINUS, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_APOSTROPHE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT_BRACKET, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_EQUAL, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_CAPS_LOCK, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_RIGHT_SHIFT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_ENTER, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_RIGHT_BRACKET, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_BACKSLASH, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_BACKSPACE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_KEYPAD_1, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_KEYPAD_4, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_7, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_KEYPAD_0, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_DECIMAL, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_2, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_5, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_6, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_8, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_ESCAPE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_NUM_LOCK, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_F11, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_ADD, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_3, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_SUBSTRACT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_MULTIPLY, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_KEYPAD_9, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_SCROLL_LOCK, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_ALT_SYSRQ, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED}, // For some laptop keyboards
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_F7, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_ALT_SYSRQ, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED}
};

static PS2KeyboardMapKey g_scanCode2SingleByteReleaseSet[133] = {
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_F9, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F7, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED}, // F7 is 0x02 on some laptop keyboards
    {DEXPROS_KEY_F5, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F3, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F1, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F2, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F12, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_F10, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F8, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F6, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F4, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_TAB, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_GRAVE_ACCENT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT_ALT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_LEFT_SHIFT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT_CONTROL, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_Q, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_1, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_Z, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_S, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_A, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_W, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_2, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_C, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_X, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_D, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_E, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_4, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_3, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_SPACE, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_V, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_T, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_R, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_5, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_N, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_B, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_H, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_G, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_Y, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_6, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_M, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_J, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_U, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_7, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_8, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_COMMA, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_K, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_I, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_O, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_0, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_9, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_PERIOD, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_SLASH, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_L, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_SEMICOLON, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_P, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MINUS, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_APOSTROPHE, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT_BRACKET, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_EQUAL, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_CAPS_LOCK, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_RIGHT_SHIFT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_ENTER, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_RIGHT_BRACKET, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_BACKSLASH, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_BACKSPACE, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_KEYPAD_1, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_KEYPAD_4, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_7, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_KEYPAD_0, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_DECIMAL, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_2, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_5, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_6, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_8, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_ESCAPE, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_NUM_LOCK, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_F11, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_ADD, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_3, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_SUBSTRACT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_MULTIPLY, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_KEYPAD_9, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_SCROLL_LOCK, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_ALT_SYSRQ, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED}, // For some laptop keyboards
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_F7, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_ALT_SYSRQ, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED}
};

static PS2KeyboardMapKey g_scanCode2TwoBytesSet[127] = {
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_WWW_SEARCH, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_RIGHT_ALT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_RIGHT_CONTROL, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MULTIMEDIA_PREVIOUS_TRACK, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_WWW_FAVOURITES, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT_SUPER, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MULTIMEDIA_WWW_REFRESH, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MULTIMEDIA_VOLUME_DOWN, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_MUTE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_RIGHT_SUPER, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MULTIMEDIA_WWW_STOP, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_CALCULATOR, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MENU, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MULTIMEDIA_WWW_FORWARD, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_VOLUME_UP, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_PLAY_PAUSE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_ACPI_POWER, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MULTIMEDIA_WWW_BACK, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_WWW_HOME, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MULTIMEDIA_STOP, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_ACPI_SLEEP, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_MULTIMEDIA_MY_COMPUTER, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_EMAIL, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_SLASH, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_NEXT_TRACK, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_MEDIA_SELECT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_KEYPAD_ENTER, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_ACPI_WAKE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_END, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_HOME, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_INSERT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_DELETE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_DOWN, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_RIGHT, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_UP, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_PAGE_DOWN, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_PAGE_UP, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    {DEXPROS_KEY_CONTROL_BREAK, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED}
};

static PS2KeyboardMapKey g_scanCode2TwoBytesReleaseSet[127] = {
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_WWW_SEARCH, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_RIGHT_ALT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_RIGHT_CONTROL, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MULTIMEDIA_PREVIOUS_TRACK, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_WWW_FAVOURITES, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT_SUPER, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MULTIMEDIA_WWW_REFRESH, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MULTIMEDIA_VOLUME_DOWN, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_MUTE, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_RIGHT_SUPER, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MULTIMEDIA_WWW_STOP, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_CALCULATOR, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MENU, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MULTIMEDIA_WWW_FORWARD, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_VOLUME_UP, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_PLAY_PAUSE, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_ACPI_POWER, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MULTIMEDIA_WWW_BACK, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_WWW_HOME, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MULTIMEDIA_STOP, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_ACPI_SLEEP, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_MULTIMEDIA_MY_COMPUTER, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_EMAIL, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_SLASH, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_NEXT_TRACK, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_MULTIMEDIA_MEDIA_SELECT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_KEYPAD_ENTER, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_ACPI_WAKE, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_END, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_LEFT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_HOME, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_INSERT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_DELETE, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_DOWN, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_RIGHT, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_UP, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE}, {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_PAGE_DOWN, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {0, DEXPROS_PS2K_NONE},
    {0, DEXPROS_PS2K_NONE},
    {DEXPROS_KEY_PAGE_UP, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    {DEXPROS_KEY_CONTROL_BREAK, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED}
};


static uint8_t g_scanCode2Level2PrtScnReleaseBytes[4] = {
    0x7C, 0xE0, 0xF0, 0x12
};
static PS2KeyboardSpecialSequence g_scanCode2Level2PrtScnReleaseSequence = {
    .key = {DEXPROS_KEY_PRINT_SCREEN, DEXPROS_PS2KEYBOARD_KEY_ACTION_RELEASED},
    .pSequence = g_scanCode2Level2PrtScnReleaseBytes,
    .sequenceLength = 4
};


static uint8_t g_scanCode2Level1PrtScnPressedBytes[3] = {
    0x12, 0xE0, 0x7C
};
static PS2KeyboardSpecialSequence g_scanCode2Level1PrtScnPressedSequence = {
    .key = {DEXPROS_KEY_PRINT_SCREEN, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED},
    .pSequence = g_scanCode2Level1PrtScnPressedBytes,
    .sequenceLength = 3
};

static uint8_t g_scanCode2PauseKeyBytes[8] = {
    0xE1, 0x14, 0x77, 0xE1, 0xF0, 0x14, 0xF0, 0x77
};
static PS2KeyboardSpecialSequence g_scanCode2PauseSequence = {
    .key = {DEXPROS_KEY_PAUSE, DEXPROS_PS2KEYBOARD_KEY_ACTION_PRESSED_RELEASED},
    .pSequence = g_scanCode2PauseKeyBytes,
    .sequenceLength = 8
};


static PS2KeyboardScanCodes g_scanCode2Level2SubTables[1] = {
    {
        .pKeysPerByte = g_scanCode2TwoBytesReleaseSet,
        .numKeysPerByte = 127,
        .pByteExtendedScanCodes = NULL,
        .pByteExtendCodes = NULL,
        .numByteExtendCodes = 0,
        .pSpecialSequences = &g_scanCode2Level2PrtScnReleaseSequence,
        .numSpecialSequences = 1
    },
};
static uint8_t g_scanCode2Level2ExtendCodes[1] = {
    0xF0
};


static PS2KeyboardScanCodes g_scanCode2Level1SubTables[2] = {
    {
        .pKeysPerByte = g_scanCode2TwoBytesSet,
        .numKeysPerByte = 127,
        .pByteExtendedScanCodes = g_scanCode2Level2SubTables,
        .pByteExtendCodes = g_scanCode2Level2ExtendCodes,
        .numByteExtendCodes = 1,
        .pSpecialSequences = &g_scanCode2Level1PrtScnPressedSequence,
        .numSpecialSequences = 1
    },
    {
        .pKeysPerByte = g_scanCode2SingleByteReleaseSet,
        .numKeysPerByte = 133,
        .pByteExtendedScanCodes = NULL,
        .pByteExtendCodes = NULL,
        .numByteExtendCodes = 0,
        .pSpecialSequences = NULL,
        .numSpecialSequences = 0
    }
};
static uint8_t g_scanCode2Level1ExtendCodes[2] = {
    0xE0,
    0xF0
};


static PS2KeyboardScanCodes g_scanCode2SetGlobal = {
    .pKeysPerByte = g_scanCode2SingleByteSet,
    .numKeysPerByte = 133,
    .pByteExtendedScanCodes = g_scanCode2Level1SubTables,
    .pByteExtendCodes = g_scanCode2Level1ExtendCodes,
    .numByteExtendCodes = 2,
    .pSpecialSequences = &g_scanCode2PauseSequence,
    .numSpecialSequences = 1
};

inline static const void* DexprOS_PS2ScanCode2RellocatePointer(const void* pointer,
                                                               DexprOS_VirtualMemoryAddress kernelOffset)
{
    if ((DexprOS_VirtualMemoryAddress)pointer > kernelOffset)
        return pointer;
    if (pointer == NULL)
        return NULL;
    return (const void*)((DexprOS_VirtualMemoryAddress)pointer + kernelOffset);
}

static void DexprOS_RellocatePS2KeyboardScanCode2Pointers(DexprOS_VirtualMemoryAddress kernelOffset)
{
    g_scanCode2Level2PrtScnReleaseSequence.pSequence =
    (const uint8_t*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level2PrtScnReleaseSequence.pSequence,
                                                         kernelOffset);

    g_scanCode2Level1PrtScnPressedSequence.pSequence =
    (const uint8_t*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level1PrtScnPressedSequence.pSequence,
                                                         kernelOffset);

    g_scanCode2PauseSequence.pSequence =
    (const uint8_t*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2PauseSequence.pSequence,
                                                         kernelOffset);

    g_scanCode2Level2SubTables[0].pKeysPerByte =
    (const PS2KeyboardMapKey*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level2SubTables[0].pKeysPerByte,
                                                                   kernelOffset);

    g_scanCode2Level2SubTables[0].pSpecialSequences =
    (const PS2KeyboardSpecialSequence*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level2SubTables[0].pSpecialSequences,
                                                                            kernelOffset);

    g_scanCode2Level1SubTables[0].pKeysPerByte =
    (const PS2KeyboardMapKey*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level1SubTables[0].pKeysPerByte,
                                                                   kernelOffset);

    g_scanCode2Level1SubTables[0].pByteExtendedScanCodes =
    (const PS2KeyboardScanCodes*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level1SubTables[0].pByteExtendedScanCodes,
                                                                      kernelOffset);

    g_scanCode2Level1SubTables[0].pByteExtendCodes =
    (const uint8_t*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level1SubTables[0].pByteExtendCodes,
                                                         kernelOffset);

    g_scanCode2Level1SubTables[0].pSpecialSequences =
    (const PS2KeyboardSpecialSequence*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level1SubTables[0].pSpecialSequences,
                                                                            kernelOffset);

    g_scanCode2Level1SubTables[1].pKeysPerByte =
    (const PS2KeyboardMapKey*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2Level1SubTables[1].pKeysPerByte,
                                                                   kernelOffset);

    g_scanCode2SetGlobal.pKeysPerByte =
    (const PS2KeyboardMapKey*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2SetGlobal.pKeysPerByte,
                                                                   kernelOffset);

    g_scanCode2SetGlobal.pByteExtendedScanCodes =
    (const PS2KeyboardScanCodes*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2SetGlobal.pByteExtendedScanCodes,
                                                                      kernelOffset);

    g_scanCode2SetGlobal.pByteExtendCodes =
    (const uint8_t*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2SetGlobal.pByteExtendCodes,
                                                         kernelOffset);

    g_scanCode2SetGlobal.pSpecialSequences =
    (const PS2KeyboardSpecialSequence*)DexprOS_PS2ScanCode2RellocatePointer(g_scanCode2SetGlobal.pSpecialSequences,
                                                                            kernelOffset);
}


#endif // DEXPROS_DRIVERS_KEYBOARD_PS2KEYBOARDSCANCODES_H_INCLUDED
