#ifndef DEXPROS_KERNEL_KEYBOARDINPUT_H_INCLUDED
#define DEXPROS_KERNEL_KEYBOARDINPUT_H_INCLUDED

#ifdef __cplusplus
extern "C"
{
#endif


typedef unsigned short DexprOS_KeyID;

typedef enum DexprOS_KeyState
{
    DEXPROS_KEY_STATE_RELEASED = 0,
    DEXPROS_KEY_STATE_PRESSED = 1,
    DEXPROS_KEY_STATE_REPEAT = 2
} DexprOS_KeyState;


#define DEXPROS_KEY_UNKNOWN 0
#define DEXPROS_KEY_0 48
#define DEXPROS_KEY_1 49
#define DEXPROS_KEY_2 50
#define DEXPROS_KEY_3 51
#define DEXPROS_KEY_4 52
#define DEXPROS_KEY_5 53
#define DEXPROS_KEY_6 54
#define DEXPROS_KEY_7 55
#define DEXPROS_KEY_8 56
#define DEXPROS_KEY_9 57
#define DEXPROS_KEY_A 65
#define DEXPROS_KEY_B 66
#define DEXPROS_KEY_C 67
#define DEXPROS_KEY_D 68
#define DEXPROS_KEY_E 69
#define DEXPROS_KEY_F 70
#define DEXPROS_KEY_G 71
#define DEXPROS_KEY_H 72
#define DEXPROS_KEY_I 73
#define DEXPROS_KEY_J 74
#define DEXPROS_KEY_K 75
#define DEXPROS_KEY_L 76
#define DEXPROS_KEY_M 77
#define DEXPROS_KEY_N 78
#define DEXPROS_KEY_O 79
#define DEXPROS_KEY_P 80
#define DEXPROS_KEY_Q 81
#define DEXPROS_KEY_R 82
#define DEXPROS_KEY_S 83
#define DEXPROS_KEY_T 84
#define DEXPROS_KEY_U 85
#define DEXPROS_KEY_V 86
#define DEXPROS_KEY_W 87
#define DEXPROS_KEY_X 88
#define DEXPROS_KEY_Y 89
#define DEXPROS_KEY_Z 90
#define DEXPROS_KEY_SPACE 32
#define DEXPROS_KEY_MINUS 45
#define DEXPROS_KEY_EQUAL 61
#define DEXPROS_KEY_LEFT_BRACKET 91
#define DEXPROS_KEY_RIGHT_BRACKET 93
#define DEXPROS_KEY_SEMICOLON 59
#define DEXPROS_KEY_APOSTROPHE 39
#define DEXPROS_KEY_COMMA 44
#define DEXPROS_KEY_PERIOD 46
#define DEXPROS_KEY_SLASH 47
#define DEXPROS_KEY_BACKSLASH 92
#define DEXPROS_KEY_GRAVE_ACCENT 96
#define DEXPROS_KEY_DELETE 127
#define DEXPROS_KEY_TAB 256
#define DEXPROS_KEY_CAPS_LOCK 257
#define DEXPROS_KEY_SCROLL_LOCK 258
#define DEXPROS_KEY_NUM_LOCK 259
#define DEXPROS_KEY_LEFT_SHIFT 260
#define DEXPROS_KEY_LEFT_CONTROL 261
#define DEXPROS_KEY_LEFT_SUPER 262
#define DEXPROS_KEY_LEFT_ALT 263
#define DEXPROS_KEY_MENU 265
#define DEXPROS_KEY_ENTER 266
#define DEXPROS_KEY_BACKSPACE 267
#define DEXPROS_KEY_ESCAPE 268
#define DEXPROS_KEY_RIGHT_ALT 400
#define DEXPROS_KEY_RIGHT_SUPER 401
#define DEXPROS_KEY_RIGHT_CONTROL 402
#define DEXPROS_KEY_RIGHT_SHIFT 403
#define DEXPROS_KEY_F1 271
#define DEXPROS_KEY_F2 272
#define DEXPROS_KEY_F3 273
#define DEXPROS_KEY_F4 274
#define DEXPROS_KEY_F5 275
#define DEXPROS_KEY_F6 276
#define DEXPROS_KEY_F7 277
#define DEXPROS_KEY_F8 278
#define DEXPROS_KEY_F9 279
#define DEXPROS_KEY_F10 280
#define DEXPROS_KEY_F11 281
#define DEXPROS_KEY_F12 282
#define DEXPROS_KEY_PRINT_SCREEN 297
#define DEXPROS_KEY_PAUSE 298
#define DEXPROS_KEY_HOME 299
#define DEXPROS_KEY_PAGE_UP 300
#define DEXPROS_KEY_PAGE_DOWN 301
#define DEXPROS_KEY_END 302
#define DEXPROS_KEY_INSERT 303
#define DEXPROS_KEY_LEFT 304
#define DEXPROS_KEY_RIGHT 305
#define DEXPROS_KEY_UP 306
#define DEXPROS_KEY_DOWN 307
#define DEXPROS_KEY_ALT_SYSRQ 308
#define DEXPROS_KEY_CONTROL_BREAK 309
#define DEXPROS_KEY_KEYPAD_0 310
#define DEXPROS_KEY_KEYPAD_1 311
#define DEXPROS_KEY_KEYPAD_2 312
#define DEXPROS_KEY_KEYPAD_3 313
#define DEXPROS_KEY_KEYPAD_4 314
#define DEXPROS_KEY_KEYPAD_5 315
#define DEXPROS_KEY_KEYPAD_6 316
#define DEXPROS_KEY_KEYPAD_7 317
#define DEXPROS_KEY_KEYPAD_8 318
#define DEXPROS_KEY_KEYPAD_9 319
#define DEXPROS_KEY_KEYPAD_DECIMAL 320
#define DEXPROS_KEY_KEYPAD_DEVIDE 321
#define DEXPROS_KEY_KEYPAD_MULTIPLY 322
#define DEXPROS_KEY_KEYPAD_SUBSTRACT 323
#define DEXPROS_KEY_KEYPAD_ADD 324
#define DEXPROS_KEY_KEYPAD_ENTER 325
#define DEXPROS_KEY_KEYPAD_EQUAL 326
#define DEXPROS_KEY_ACPI_POWER 327
#define DEXPROS_KEY_ACPI_SLEEP 328
#define DEXPROS_KEY_ACPI_WAKE 329
#define DEXPROS_KEY_MULTIMEDIA_WWW_SEARCH 330
#define DEXPROS_KEY_MULTIMEDIA_WWW_FAVOURITES 331
#define DEXPROS_KEY_MULTIMEDIA_WWW_REFRESH 332
#define DEXPROS_KEY_MULTIMEDIA_WWW_STOP 333
#define DEXPROS_KEY_MULTIMEDIA_WWW_FORWARD 334
#define DEXPROS_KEY_MULTIMEDIA_WWW_BACK 335
#define DEXPROS_KEY_MULTIMEDIA_WWW_HOME 336
#define DEXPROS_KEY_MULTIMEDIA_MY_COMPUTER 337
#define DEXPROS_KEY_MULTIMEDIA_EMAIL 338
#define DEXPROS_KEY_MULTIMEDIA_CALCULATOR 339
#define DEXPROS_KEY_MULTIMEDIA_VOLUME_DOWN 340
#define DEXPROS_KEY_MULTIMEDIA_VOLUME_UP 341
#define DEXPROS_KEY_MULTIMEDIA_MUTE 342
#define DEXPROS_KEY_MULTIMEDIA_PREVIOUS_TRACK 343
#define DEXPROS_KEY_MULTIMEDIA_NEXT_TRACK 344
#define DEXPROS_KEY_MULTIMEDIA_PLAY_PAUSE 345
#define DEXPROS_KEY_MULTIMEDIA_STOP 346
#define DEXPROS_KEY_MULTIMEDIA_MEDIA_SELECT 347
#define DEXPROS_KEY_Max 512


#ifdef __cplusplus
}
#endif

#endif // DEXPROS_KERNEL_KEYBOARDINPUT_H_INCLUDED
